dubbo:
  consumer:
    check: true
    timeout: 10000
  application:
    name: custom
  registry:
    address: zookeeper://192.168.0.241:2181

server:
  port: 8082
spring:
  profiles:
    include: mapper
